### ISSUE TITLE
[ Bug ] Gold count does not update at all.

### ISSUE THREAD

**Issue by PSSMT** [RCVolus/league-prod-toolkit#329] opened 2023-04-21 17:54 UTC
**Describe the bug**

**To Reproduce**

2. Click on '...'
3. Scroll down to '...'

**Expected behavior**

**Screenshots**

**System:**

- Node: [e.g. 16.4]
- Prod Tool Version: [e.g. 1.3.0]
- Observer Tool Version: [e.g. 1.0.0]
- Streaming Software & Version: (If it is a problem while streaming or testing)
- Browser: [e.g. chrome, safari]

**Additional context**

**Comment by Freeedooo** [comment] 2023-04-22 06:54
same here

**Comment by sdomi4** [comment] 2023-04-22 08:54
Looks like a bug; offsets are correct for gold.

**Comment by PSSMT** [comment] 2023-04-22 11:53
I've tried reinstalling everything. Watching a replay, live match from lobby etc.

**Comment by FireFoXz09** [comment] 2023-04-22 17:32
Same. I tried other software and tools, and it works everywhere else, but not with RCVolus Toolkit. (Both offsets seems to be fine)

**Comment by sdomi4** [comment] 2023-04-26 13:55
We haven't been able to find an issue with the tool so far; it might still be an issue with offsets. We are still investigating.

**Comment by Coow** [comment] 2023-04-30 10:40
@sdomi4 I believe the issue is on the Web side of things, as the offsets are all correct. The UI or anything doesn't seem to update at all, but the Scoreboard is updated in the backend, and with a refresh of the page it updates. Could it be related to a recent package update that broke a function that the Ingame Module relied on?

**Comment by Himyu** [comment] 2023-04-30 16:23
It has nothing to do with the prod tool itself. It's a problem with the observer tool or the farsight module we use to get the gold since it does not currently give any information on the champions. unfortunately, until this issue is fixed it will stay like this.

**Comment by Himyu** [comment] 2023-05-03 19:44
Should be fixed with the newest version of the observer tool https://github.com/RCVolus/league-observer-tool/releases

**Closed as completed by Himyu** 2023-05-03 19:44 UTC
Labels: bug
