### ISSUE TITLE
[ Bug ] Inhibitor down picture flash instead of progressing (like baron power-play)

### ISSUE THREAD

**Issue by FireFoXz09** [RCVolus/league-prod-toolkit#545] opened 2023-11-22 03:35 UTC
**Describe the bug**
Inhibitor pictures flash/refresh at an innacurate rate, making it blink plain at every seconds instead or acting like a "progress bar"

**To Reproduce**

1. Launch a game
2. Activate everything in Observer Tool
3. Wait until an inhibitor is destroyed and activate the inhib overlay in the in-game tab of the toolkit
4. Profit?

**Expected behavior**
A clear "progress effect", like for the baron power play, instead of a blinking icon.

**Screenshots**
![inhib bug](https://github.com/RCVolus/league-prod-toolkit/assets/89284738/d7cf34b4-269b-4ac2-8b71-caa7df11390a)

Video Link : [Twitch Clip of the bug](https://clips.twitch.tv/GloriousAssiduousArugulaKappaClaus-DKBR4hyGdPzeqzy_)

**System:**

- OS: Windows 10
- Node: Verison 16.7
- Prod Tool Version: 1.7.7 (but it's been doing this in version 1.7.5 and 1.7.4 too. Before that I don't know)
- Observer Tool Version: 6.7.3 (but it was also doing this with 6.7.2, earlier I can't say.)
- Streaming Software & Version: OBS Studio 29.1.3
- Browser: Opera GX

**Comment by Himyu** [comment] 2023-11-30 19:18
This issue was caused by two functions trying to update the inhibitors at the same time. The behavior was removed and this issue was fixed with the newest patch to the in-game module.

**Comment by FireFoXz09** [comment] 2023-12-01 02:51
I'm gonna test it next week on my side, thanks for the update!

**Closed as completed** 2023-12-11 13:21 UTC
Labels: bug
