### ISSUE TITLE
[ Bug ] Objectives timers bugged

### ISSUE THREAD

**Issue by FireFoXz09** [RCVolus/league-prod-toolkit#216] opened 2023-01-24 02:48 UTC
When a Dragon, Herald or Baron is slain, the pop-up always give the 15:25 time. (Wich is the exact time used in the "Test Event" function)

![image](https://user-images.githubusercontent.com/89284738/214202203-7d659c5e-6919-4ba4-b36a-3994ddf28105.png)

**Comment by Himyu** [comment] 2023-01-24 10:21
Yes, you are right. It's caused by this line of code https://github.com/rcv-prod-toolkit/module-league-in-game/blob/main/frontend/gfx/ingame.js#L352
For a quick fix just remove the /* and */ and we will fix it asap as well

**Comment by Himyu** [comment] 2023-01-31 00:21
This is fixed with the newest patched https://github.com/rcv-prod-toolkit/module-league-in-game/releases/tag/v3.6.1

**Closed as completed by Himyu** 2023-01-31 00:21 UTC
Labels: bug
