### ISSUE TITLE
[ Bug ] Erorr when trying to get match data

### ISSUE THREAD

**Issue by shir0xyz** [RCVolus/league-prod-toolkit#514] opened 2023-10-19 01:35 UTC
A following error is showing up when trying to get match data after the game ended

Prod toolkit version 1.7.1

![image](https://github.com/RCVolus/league-prod-toolkit/assets/48430352/834b69ad-05cd-4568-a319-3297679feac6)

**Comment by sdomi4** [comment] 2023-10-20 07:56
There have been some issues with API calls being made too early recently. Does manually looking up the game through league-state work after the game is over?

Which region are you in?

**Comment by MDvorky** [comment] 2023-10-23 10:23
I have this issue as well. I did not update yet.

**Comment by Himyu** [comment] 2023-11-21 12:46
duplicate of #430

**Closed as completed by Himyu** 2023-11-21 12:46 UTC
Labels: bug
